export const movies = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Godfather: Part II",
  "The Dark Knight",
  "Pulp Fiction",
  "The Good, the Bad and the Ugly",
  "12 Angry Men",
  "Schindler's List",
  "The Lord of the Rings: The Return of the King",
  "Fight Club",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Star Wars: Episode V - The Empire Strikes Back",
  "Inception",
  "One Flew Over the Cuckoo's Nest",
  "Seven Samurai",
  "Goodfellas",
  "Star Wars: Episode IV - A New Hope",
  "Forrest Gump",
  "The Lord of the Rings: The Two Towers",
  "The Matrix",
  "City of God",
  "Once Upon a Time in the West",
  "Casablanca",
  "Se7en",
  "The Usual Suspects",
  "The Silence of the Lambs",
  "It's a Wonderful Life",
  "Rear Window",
  "Indiana Jones and the Raiders of the Lost Ark",
  "Léon: The Professional",
  "Psycho",
  "Sunset Blvd.",
  "City Lights",
  "The Dark Knight Rises",
  "American History X",
  "Apocalypse Now",
  "Memento",
  "Spirited Away",
  "Modern Times",
  "Saving Private Ryan",
  "Terminator 2: Judgment Day",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "The Intouchables",
  "Alien",
  "Django Unchained",
  "North by Northwest",
  "Life Is Beautiful",
  "M",
  "Paths of Glory",
  "Citizen Kane",
  "Back to the Future",
  "Double Indemnity",
  "The Pianist",
  "The Departed",
  "The Shining",
  "Vertigo",
  "The Great Dictator",
  "The Lives of Others",
  "Gladiator",
  "Aliens",
  "American Beauty",
  "The Green Mile",
  "WALL·E",
  "Toy Story 3",
  "Taxi Driver",
  "Amélie",
  "A Separation",
  "The Prestige",
  "Cinema Paradiso",
  "Lawrence of Arabia",
  "A Clockwork Orange",
  "To Kill a Mockingbird",
  "Das Boot",
  "The Treasure of the Sierra Madre",
  "The Third Man",
  "Reservoir Dogs",
  "The Lion King",
  "Requiem for a Dream",
  "Once Upon a Time in America",
  "Eternal Sunshine of the Spotless Mind",
  "Bicycle Thieves",
  "Grave of the Fireflies",
  "Witness for the Prosecution",
  "Singin' in the Rain",
  "Princess Mononoke",
  "Braveheart",
  "Star Wars: Episode VI - Return of the Jedi",
  "All About Eve",
  "Oldboy",
  "Rashomon",
  "Metropolis",
  "Full Metal Jacket",
  "Monty Python and the Holy Grail",
  "Some Like It Hot",
  "Chinatown",
  "The Apartment",
  "L.A. Confidential",
  "Amadeus",
  "The Sting",
  "Yojimbo",
  "2001: A Space Odyssey",
  "Like Stars on Earth",
  "Unforgiven",
  "Raging Bull",
  "The Bridge on the River Kwai",
  "Mr. Smith Goes to Washington",
  "The General",
  "Indiana Jones and the Last Crusade",
  "Batman Begins",
  "Ikiru",
  "For a Few Dollars More",
  "On the Waterfront",
  "The Kid",
  "Die Hard",
  "The Great Escape",
  "Snatch",
  "Downfall",
  "Inglourious Basterds",
  "The Seventh Seal",
  "Pan's Labyrinth",
  "Wild Strawberries",
  "Up",
  "Toy Story",
  "The Maltese Falcon",
  "The Elephant Man",
  "Rebecca",
  "Heat",
  "3 Idiots",
  "Ran",
  "Blade Runner",
  "Scarface",
  "The Avengers",
  "The Gold Rush",
  "Touch of Evil",
  "Rang De Basanti",
  "The Big Lebowski",
  "Gran Torino",
  "It Happened One Night",
  "Cool Hand Luke",
  "Fargo",
  "Warrior",
  "The Deer Hunter",
  "The Secret in Their Eyes",
  "My Neighbor Totoro",
  "The Grapes of Wrath",
  "Lock, Stock and Two Smoking Barrels",
  "Strangers on a Train",
  "The Best Years of Our Lives",
  "High Noon",
  "Gone with the Wind",
  "Sin City",
  "Casino",
  "V for Vendetta",
  "Good Will Hunting",
  "Butch Cassidy and the Sundance Kid",
  "The Thing",
  "No Country for Old Men",
  "Trainspotting",
  "Hotel Rwanda",
  "The Wizard of Oz",
  "Notorious",
  "Platoon",
  "The Sixth Sense",
  "Star Trek Into Darkness",
  "Jaws",
  "The Night of the Hunter",
  "Into the Wild",
  "Annie Hall",
  "How to Train Your Dragon",
  "Kill Bill: Vol. 1",
  "Dial M for Murder",
  "The Big Sleep",
  "Mary and Max",
  "Persona",
  "Monty Python's Life of Brian",
  "Network",
  "The 400 Blows",
  "Finding Nemo",
  "Ben-Hur",
  "Donnie Darko",
  "Howl's Moving Castle",
  "The King's Speech",
  "There Will Be Blood",
  "Stand by Me",
  "The Killing",
  "The Princess Bride",
  "Million Dollar Baby",
  "La Strada",
  "Who's Afraid of Virginia Woolf?",
  "Amores Perros",
  "8½",
  "The Terminator",
  "The Hobbit: An Unexpected Journey",
  "Fanny and Alexander",
  "Stalker",
  "Gandhi",
  "Groundhog Day",
  "Dog Day Afternoon",
  "The Bourne Ultimatum",
  "Incendies",
  "12 Monkeys",
  "The Hustler",
  "Anatomy of a Murder",
  "Memories of Murder",
  "Life of Pi",
  "Stalag 17",
  "A Beautiful Mind",
  "Hachi: A Dog's Tale",
  "The Man Who Shot Liberty Valance",
  "Black Swan",
  "The Graduate",
  "Sleuth",
  "Harry Potter and the Deathly Hallows: Part 2",
  "The Manchurian Candidate",
  "Barry Lyndon",
  "The Wild Bunch",
  "Infernal Affairs",
  "The Perks of Being a Wallflower",
  "My Sassy Girl",
  "Roman Holiday",
  "Rocky",
  "Slumdog Millionaire",
  "Ip Man",
  "In the Name of the Father",
  "Rope",
  "La Haine",
  "Nausicaä of the Valley of the Wind",
  "The Celebration",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "All Quiet on the Western Front",
  "Underground",
  "Elite Squad 2: The Enemy Within",
  "Harvey",
  "Spring, Summer, Fall, Winter... and Spring",
  "The Exorcist",
  "La Dolce Vita",
  "In the Mood for Love",
  "The Artist",
  "Three Colors: Red",
  "A Streetcar Named Desire",
  "Star Trek",
  "Battleship Potemkin",
  "Bringing Up Baby",
  "The Diving Bell and the Butterfly",
  "Monsters, Inc.",
  "Rio Bravo",
  "Castle in the Sky",
  "His Girl Friday",
  "A Fistful of Dollars",
  "The Help",
  "The Cabinet of Dr. Caligari",
  "The Philadelphia Story",
  "Arsenic and Old Lace",
  "The Truman Show",
  "Shutter Island",
  "Papillon",
  "A Christmas Story",
  "Beauty and the Beast",
  "Ratatouille",
  "District 9",
  "Shadow of a Doubt",
  "Before Sunrise",
  "The Searchers",
  "Jurassic Park",
  "Duck Soup",
  "In the Heat of the Night",
  "Solaris",
  "Charade",
  "Nosferatu",
  "Chungking Express",
  "The Lady Vanishes",
  "Aguirre, the Wrath of God",
  "Patton",
  "Paris, Texas",
  "The Adventures of Robin Hood",
  "Rosemary's Baby",
  "Manhattan",
  "The Nightmare Before Christmas",
  "Frankenstein",
  "Harold and Maude",
  "King Kong",
  "Rain Man",
  "The Sea Inside",
  "All the President's Men",
  "Black Cat, White Cat",
  "Big Fish",
  "3-Iron",
  "Magnolia",
  "Dawn of the Dead",
  "Let the Right One In",
  "JFK",
  "Night of the Living Dead",
  "Shaun of the Dead",
  "Young Frankenstein",
  "Mystic River",
  "The Straight Story",
  "Spartacus",
  "The Untouchables",
  "The Conversation",
  "Planet of the Apes",
  "Edward Scissorhands",
  "Wings of Desire",
  "Blood Diamond",
  "The Wrestler",
  "The African Queen",
  "Before Sunset",
  "Being There",
  "Doctor Zhivago",
  "Bonnie and Clyde",
  "Dances with Wolves",
  "Kill Bill: Vol. 2",
  "Sling Blade",
  "The Incredibles",
  "Crimes and Misdemeanors",
  "Ed Wood",
  "Brazil",
  "This Is the End",
  "Elite Squad",
  "Talk to Her",
  "Moon",
  "In Bruges",
  "This Is Spinal Tap",
  "Avatar",
  "Akira",
  "Midnight Cowboy",
  "Letters from Iwo Jima",
  "Toy Story 2",
  "Persepolis",
  "Mulholland Drive",
  "Casino Royale",
  "Children of Men",
  "True Romance",
  "A Prophet",
  "No Man's Land",
  "Cinderella Man",
  "The Man Who Would Be King",
  "The Insider",
  "Head-On",
  "Miller's Crossing",
  "Aladdin",
  "Dogville",
  "Hero",
  "Catch Me If You Can",
  "Breathless",
  "Silver Linings Playbook",
  "Almost Famous",
  "The Man from Earth",
  "Crash",
  "Glory",
  "Shrek",
  "The Killing Fields",
  "Serenity",
  "The Blues Brothers",
  "The Legend of 1900",
  "The Notebook",
  "The Fighter",
  "Hannah and Her Sisters",
  "Iron Man",
  "Badlands",
  "The Breakfast Club",
  "Once",
  "The Remains of the Day",
  "Argo",
  "The 39 Steps",
  "Three Colors: Blue",
  "Halloween",
  "Drive",
  "Little Miss Sunshine",
  "The Girl with the Dragon Tattoo",
  "The Bourne Identity",
  "The Sound of Music",
  "The Killer",
  "E.T. the Extra-Terrestrial",
  "Crouching Tiger, Hidden Dragon",
  "Taken",
  "Dead Poets Society",
  "The Day the Earth Stood Still",
  "The French Connection",
  "Carlito's Way",
  "The Social Network",
  "4 Months, 3 Weeks and 2 Days",
  "The Right Stuff",
  "Glengarry Glen Ross",
  "Hard Boiled",
  "The Iron Giant",
  "Boogie Nights",
  "Hot Fuzz",
  "Amour",
  "The Outlaw Josey Wales",
  "Ferris Bueller's Day Off",
  "Walk the Line",
  "Ghost in the Shell",
  "Rebel Without a Cause",
  "Predator",
  "Dancer in the Dark",
  "My Fair Lady",
  "All About My Mother",
  "The Birds",
  "Black Book",
  "Wreck-It Ralph",
  "Clerks",
  "Dirty Harry",
  "Scent of a Woman",
  "The Pursuit of Happyness",
  "The Ten Commandments",
  "Office Space",
  "Moonrise Kingdom",
  "Do the Right Thing",
  "The Fall",
  "The Magnificent Seven",
  "Man of Steel",
  "Deliverance",
  "Pink Floyd: The Wall",
  "500 Days of Summer",
  "The Hangover",
  "Misery",
  "Evil Dead II",
  "Run Lola Run",
  "The Curious Case of Benjamin Button",
  "The Dirty Dozen",
  "The Girl with the Dragon Tattoo",
  "Goldfinger",
  "Kick-Ass",
  "The Boondock Saints",
  "Fantasia",
  "The World's Fastest Indian",
  "My Left Foot",
  "X-Men: First Class",
  "American Gangster",
  "Kiki's Delivery Service",
  "Blue Velvet",
  "Ghostbusters",
  "Willy Wonka & the Chocolate Factory",
  "Lilya 4-Ever",
  "Airplane!",
  "Tangled",
  "Skyfall",
  "Being John Malkovich",
  "The Fugitive",
  "Battle Royale",
  "Breaking the Waves",
  "Gattaca",
  "Mr. Nobody",
  "50/50",
  "Lost in Translation",
  "Changeling",
  "Mississippi Burning",
  "O Brother, Where Art Thou?",
  "3:10 to Yuma",
  "The Last Emperor",
  "Apocalypto",
  "Snow White and the Seven Dwarfs",
  "The Motorcycle Diaries",
  "I Saw the Devil",
  "Open Your Eyes",
  "The Experiment",
  "Fantastic Mr. Fox",
  "Serpico",
  "Breakfast at Tiffany's",
  "Donnie Brasco",
  "Atonement",
  "The Longest Day",
  "The White Ribbon",
  "Finding Neverland",
  "Dark City",
  "True Grit",
  "The Boy in the Striped Pajamas",
  "As Good as It Gets",
  "The Last of the Mohicans",
  "Close Encounters of the Third Kind",
  "The Chorus",
  "Porco Rosso",
  "The Machinist",
  "Gone Baby Gone",
  "Cabaret",
  "300",
  "25th Hour",
  "South Park: Bigger, Longer & Uncut",
  "Zombieland",
  "The Triplets of Belleville",
  "The Game",
  "In America",
  "Frost/Nixon",
  "The Name of the Rose",
  "Road to Perdition",
  "Happiness",
  "Tombstone",
  "The Station Agent",
  "Lucky Number Slevin",
  "Delicatessen",
  "21 Grams",
  "Adaptation.",
  "Good Bye Lenin!",
  "Sabrina",
  "Empire of the Sun",
  "The Last King of Scotland",
  "Sympathy for Mr. Vengeance",
  "Kramer vs. Kramer",
  "What's Eating Gilbert Grape",
  "Blazing Saddles",
  "Pride & Prejudice",
  "Barton Fink",
  "The Bourne Supremacy",
  "Ocean's Eleven",
  "Match Point",
  "Back to the Future Part II",
  "Love Actually",
  "Stardust",
  "Blood Simple",
  "Eastern Promises",
  "A Very Long Engagement",
  "Mysterious Skin",
  "Les Misérables",
  "Kung Fu Hustle",
  "Harry Potter and the Prisoner of Azkaban",
  "Midnight in Paris",
  "Boyz n the Hood",
  "127 Hours",
  "Black Hawk Down",
  "The Visitor",
  "Grindhouse",
  "Star Wars: Episode III - Revenge of the Sith",
  "Lolita",
  "Zodiac",
  "Dead Man's Shoes",
  "Short Cuts",
  "Star Trek II: The Wrath of Khan",
  "Ray",
  "Man on Fire",
  "Kiss Kiss Bang Bang",
  "This Is England",
  "The Last Samurai",
  "Boy A",
  "Rushmore",
  "Ponyo",
  "Control",
  "The King of Comedy",
  "Mary Poppins",
  "A Bronx Tale",
  "The Hurt Locker",
  "October Sky",
  "The Butterfly Effect",
  "The Goonies",
  "Minority Report",
  "Thank You for Smoking",
  "The Player",
  "Traffic",
  "Coraline",
  "Who Framed Roger Rabbit",
  "Cloud Atlas",
  "MASH",
  "Fear and Loathing in Las Vegas",
  "Stranger Than Fiction",
  "Inside Man",
  "Saw",
  "Dead Man",
  "The Wicker Man",
  "Little Children",
  "United 93",
  "Brokeback Mountain",
  "Training Day",
  "Milk",
  "Night on Earth",
  "Show Me Love",
  "Munich",
  "A Fish Called Wanda",
  "The Producers",
  "The Color Purple",
  "Philadelphia",
  "Malcolm X",
  "Hugo",
  "Juno",
  "Paprika",
  "28 Days Later...",
  "The Blind Side",
  "Watchmen",
  "Celda 211",
  "Midnight Express",
  "Three Colors: White",
  "The City of Lost Children",
  "Lethal Weapon",
  "Lady Vengeance",
  "Sense and Sensibility",
  "Where Eagles Dare",
  "Awakenings",
  "Superbad",
  "End of Watch",
  "Primal Fear",
  "Enter the Dragon",
  "Titanic",
  "Detachment",
  "The Warriors",
  "The Jungle Book",
  "The Others",
  "Harry Potter and the Deathly Hallows: Part 1",
  "Dangerous Liaisons",
  "Sideways",
  "Pinocchio",
  "Cast Away",
  "Collateral",
  "13 Assassins",
  "Lord of War",
  "The Illusionist",
  "Y Tu Mamá También",
  "Blow-Up",
  "The Secret World of Arrietty",
  "Remember the Titans",
  "Moneyball",
  "Kung Fu Panda",
  "Fearless",
  "Dazed and Confused",
  "Billy Elliot",
  "Love Me If You Dare",
  "House of Sand and Fog",
  "The Count of Monte Cristo",
  "Wallace & Gromit: The Curse of the Were-Rabbit",
  "Shine",
  "The Road Warrior",
  "West Side Story",
  "When Harry Met Sally...",
  "The Skin I Live In",
  "Iron Man 3",
  "The Thin Red Line",
  "Despicable Me",
  "First Blood",
  "Escape from Alcatraz",
  "The Town",
  "Funny Games",
  "The Fifth Element",
  "Garden State",
  "The Kite Runner",
  "Indiana Jones and the Temple of Doom",
  "The Man Who Wasn't There",
  "The Counterfeiters",
  "The Godfather: Part III",
  "Rise of the Planet of the Apes",
  "Straw Dogs",
  "The Naked Gun: From the Files of Police Squad!",
  "Flipped",
  "Batman",
  "The Blind Swordsman: Zatoichi",
  "La Vie En Rose",
  "Volver",
  "Equilibrium",
  "Moulin Rouge!",
  "The Omen",
  "Looper",
  "Sherlock Holmes",
  "After Hours",
  "A Few Good Men",
  "The Hunt for Red October",
  "Falling Down",
  "Lost Highway",
  "Army of Darkness",
  "The Reader",
  "The Abyss",
  "The Assassination of Jesse James by the Coward Robert Ford",
  "The Guns of Navarone",
  "Leaving Las Vegas",
  "Marathon Man",
  "The Sandlot",
  "The Evil Dead",
  "Fast & Furious 6",
  "Following",
  "The Impossible",
  "American Psycho",
  "Tucker and Dale vs Evil",
  "Whale Rider",
  "The Raid: Redemption",
  "Hunger",
  "The Crow",
  "Good Night, and Good Luck.",
  "Harry Potter and the Goblet of Fire",
  "Die Hard with a Vengeance",
  "A History of Violence",
  "X2: X-Men United",
  "High Fidelity",
  "An American Werewolf in London",
  "Jackie Brown",
  "The Royal Tenenbaums",
  "Dead Man Walking",
  "House of Flying Daggers",
  "National Lampoon's Animal House",
  "Dead Alive",
  "Seven Pounds",
  "Apollo 13",
  "Doubt",
  "The Last Temptation of Christ",
  "Lincoln",
  "REC",
  "Interview with the Vampire: The Vampire Chronicles",
  "Up in the Air",
  "The Man Who Knew Too Much",
  "Field of Dreams",
  "Ice Age",
  "My Name Is Khan",
  "RoboCop",
  "The Fly",
  "Robin Hood",
  "The Little Mermaid",
  "A Simple Plan",
  "Scott Pilgrim vs. the World",
  "Blow",
  "The Place Beyond the Pines",
  "Planes, Trains & Automobiles",
  "American Splendor",
  "The Piano",
  "The Orphanage",
  "The Meaning of Life",
  "A Single Man",
  "Ghost Dog: The Way of the Samurai",
  "The Wave",
  "Ip Man 2",
  "Quiz Show",
  "Boys Don't Cry",
  "Waking Life",
  "Enemy at the Gates",
  "Star Trek: First Contact",
  "American Graffiti",
  "Midnight Run",
  "Now You See Me",
  "Perfume: The Story of a Murderer",
  "To Catch a Thief",
  "Felon",
  "Gangs of New York",
  "The Croods",
  "Elizabeth",
  "Sweeney Todd: The Demon Barber of Fleet Street",
  "Total Recall",
  "The Constant Gardener",
  "The Aviator",
  "We Need to Talk About Kevin",
  "The Texas Chain Saw Massacre",
  "Zero Dark Thirty",
  "Babel",
  "Witness",
  "Pi",
  "Reign Over Me",
  "The Wind that Shakes the Barley",
  "Source Code",
  "A Nightmare on Elm Street",
  "Jacob's Ladder",
  "The Fisher King",
  "Ghost World",
  "The Great Debaters",
  "The Ice Storm",
  "The Three Burials of Melquiades Estrada",
  "The Devil's Backbone",
  "Mean Streets",
  "The Hours",
  "Pleasantville",
  "The Painted Veil",
  "Sleepy Hollow",
  "Heavenly Creatures",
  "The Great Gatsby",
  "Green Street Hooligans",
  "Bullitt",
  "Notes on a Scandal",
  "Take Shelter",
  "Secondhand Lions",
  "Crazy, Stupid, Love.",
  "Sherlock Holmes: A Game of Shadows",
  "I Am Sam",
  "In the Bedroom",
  "Bambi",
  "Blue Valentine",
  "The Natural",
  "The Simpsons Movie",
  "Open Range",
  "The Big Blue",
  "The Proposition",
  "Spider-Man 2",
  "Everything Is Illuminated",
  "In the Loop",
  "Fried Green Tomatoes",
  "The Hurricane",
  "Raising Arizona",
  "Brick",
  "The Descendants",
  "The Queen",
  "August Rush",
  "Far from Heaven",
  "Alice in Wonderland",
  "Malena",
  "Capote",
  "Cube",
  "Poltergeist",
  "Rudy",
  "Trading Places",
  "X-Men",
  "The Mission",
  "Clerks II",
  "The Squid and the Whale",
  "Man on the Moon",
  "Beetlejuice",
  "Carrie",
  "A Perfect World",
  "2046",
  "Running Scared",
  "Nikita",
  "The Devil's Advocate",
  "Dirty Pretty Things",
  "Master and Commander: The Far Side of the World",
  "Bram Stoker's Dracula",
  "Biutiful",
  "Say Anything",
  "Transamerica",
  "Chaplin",
  "Life as a House",
  "National Lampoon's Christmas Vacation",
  "Wonder Boys",
  "Driving Miss Daisy",
  "The Adventures of Tintin",
  "Tootsie",
  "The Bucket List",
  "Suspiria",
  "My Cousin Vinny",
  "Corpse Bride",
  "Menace II Society",
  "Mission: Impossible - Ghost Protocol",
  "Bound",
  "Lars and the Real Girl",
  "The Life of David Gale",
  "Rescue Dawn",
  "Bad Education",
  "Lady and the Tramp",
  "Miracle",
  "Harry Potter and the Half-Blood Prince",
  "Sleepers",
  "Revolutionary Road",
  "The NeverEnding Story",
  "The Bridges of Madison County",
  "Best in Show",
  "Harry Potter and the Order of the Phoenix",
  "Freedom Writers",
  "Wall Street",
  "Swingers",
  "Pirate Radio",
  "Mr. Brooks",
  "Dumbo",
  "Hustle & Flow",
  "Across the Universe",
  "The Rock",
  "Precious",
  "Grosse Pointe Blank",
  "Excalibur",
  "Red Cliff",
  "The Cider House Rules",
  "Layer Cake",
  "King Kong",
  "Chasing Amy",
  "Harry Potter and the Sorcerer's Stone",
  "Michael Clayton",
  "Easy Rider",
  "Superman",
  "A Bridge Too Far",
  "Labyrinth",
  "World War Z",
  "Limitless",
  "Irreversible",
  "Fish Tank",
  "An Education",
  "Peter Pan",
  "Sleeping Beauty",
  "Rango",
  "The Next Three Days",
  "Shallow Grave",
  "Rounders",
  "Terms of Endearment",
  "The English Patient",
  "Eraserhead",
  "Invictus",
  "Spider-Man",
  "National Lampoon's Vacation",
  "Buffalo '66",
  "Angel Heart",
  "Flight",
  "Paris, je t'aime",
  "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
  "Crazy Heart",
  "Thelma & Louise",
  "Death at a Funeral",
  "Mulan",
  "Live Free or Die Hard",
  "The Hudsucker Proxy",
  "Much Ado About Nothing",
  "The Animatrix",
  "The Lincoln Lawyer",
  "Back to the Future Part III",
  "Beverly Hills Cop",
  "Jane Eyre",
  "Closer",
  "Dr. No",
  "Kung Fu Panda 2",
  "Animal Kingdom",
  "Cape Fear",
  "Before the Devil Knows You're Dead",
  "Legends of the Fall",
  "The Talented Mr. Ripley",
  "Matchstick Men",
  "Punch-Drunk Love",
  "The Ghost Writer",
  "Beasts of the Southern Wild",
  "Videodrome",
  "Home Alone",
  "Planet Terror",
  "Cinderella",
  "The Guard",
  "Ringu",
  "The Fountain",
  "Shame",
  "Me and You and Everyone We Know",
  "My Sister's Keeper",
  "Contact",
  "The Way Back",
  "Monster",
  "The Bank Job",
  "Face/Off",
  "Law Abiding Citizen",
  "The Road",
  "Dogma",
  "Wristcutters: A Love Story",
  "Pirates of the Caribbean: Dead Man's Chest",
  "Frailty",
  "The Adventures of Priscilla, Queen of the Desert",
  "Election",
  "The Crying Game",
  "Seabiscuit",
  "Cars",
  "Half Nelson",
  "Megamind",
  "Shrek 2",
  "Heathers",
  "Winter's Bone",
  "Gosford Park",
  "The Descent",
  "The Dead Zone",
  "Fast Five",
  "Sunshine",
  "Deconstructing Harry",
  "The People vs. Larry Flynt",
  "Caché",
  "RocknRolla",
  "Audition",
  "Lawless",
  "Frida",
  "Cashback",
  "The Science of Sleep",
  "Chocolat",
  "Four Lions",
  "Quills",
  "The Mist",
  "Mongol: The Rise of Genghis Khan",
  "The Emperor's New Groove",
  "Caddyshack",
  "Identity",
  "Forgetting Sarah Marshall",
  "Synecdoche, New York",
  "Submarine",
  "Harry Brown",
  "A Tale of Two Sisters",
  "Jerry Maguire",
  "Harry Potter and the Chamber of Secrets",
  "From Dusk Till Dawn",
  "Ronin",
  "Frequency",
  "In the Valley of Elah",
  "Big",
  "K-PAX",
  "Arizona Dream",
  "Black Dynamite",
  "Unbreakable",
  "Eyes Wide Shut",
  "Shaolin Soccer",
  "Seven Psychopaths",
  "Thirteen Days",
  "The Hitcher",
  "Star Trek IV: The Voyage Home",
  "A Time to Kill",
  "The Muppets",
  "Dumb and Dumber",
  "Manhunter",
  "Win Win",
  "True Lies",
  "Elephant",
  "The Terminal",
  "Enemy of the State",
  "In the Line of Fire",
  "The Negotiator",
  "Narc",
  "The Ides of March",
  "One Hundred and One Dalmatians",
  "Broken Flowers",
  "Men in Black",
  "Gremlins",
  "The 40-Year-Old Virgin",
  "A Bug's Life",
  "Jo Nesbø's Headhunters",
  "From Russia with Love",
  "The Piano Teacher",
];
